//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationMVC5Teste.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carro
    {
        public int IDcarro { get; set; }
        public string Nome { get; set; }
        public Nullable<System.DateTime> Ano { get; set; }
        public int IDmodelo { get; set; }
    
        public virtual Modelo Modelo { get; set; }
    }
}
