//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationMVC5Teste.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Modelo
    {
        public Modelo()
        {
            this.Carro = new HashSet<Carro>();
        }
    
        public int IDmodelo { get; set; }
        public string NomeModelo { get; set; }
        public string Descricao { get; set; }
    
        public virtual ICollection<Carro> Carro { get; set; }
    }
}
